runtime: python311

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: production
  PORT: 8080

handlers:
- url: /.*
  script: auto

# Cloud Run specific settings
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10