# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  # nginx Prometheus Exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']
    metrics_path: /metrics
    scrape_interval: 10s

  # nginx Status (if enabled)
  - job_name: 'nginx-status'
    static_configs:
      - targets: ['localhost:80']
    metrics_path: /nginx_status
    scrape_interval: 10s
    # Note: This requires nginx status module to be enabled

  # CDN-specific metrics
  - job_name: 'cdn-metrics'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: /metrics
    scrape_interval: 30s
    # Note: This will be implemented in Phase 2 with custom Flask metrics

  - job_name: 'nginxlog'
    static_configs:
      - targets: ['localhost:4040']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'nginx-fluentd'
    static_configs:
      - targets: ['localhost:24231']
    metrics_path: /metrics
    scrape_interval: 10s

